### ISSUE TITLE
Thanks for giving.

### ISSUE THREAD

**Issue by MutaLucem** [innat/ML-Bookmarks#1]
Thanks a lot for ur selfless contribution in which give somebody indeed the platform to update the monograph pdf which is expensive.

**Comment by innat** [comment]
Hello MutaLucem, 
As far as the **Book Materials** concern, yes I do only **inform** the top-level resources corresponding to the fields rather than sharing **openly the soft materials** of those due to **copyright issues** (some of them have). Hope you understand. However, we would cooperate if anyone reaches out via mail. Thanks.
